# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21c2a5e0ef13a88c130729d4b7aef578b8796a5fa2938d0baf8b85a99c0f2d962c863ba1555433df9e9e500c4d0c45dd638255d6f2e5587fc81805688810c8ab

test:
  secret_key_base: 9ddc39ede2aab25749511642d127213489d1ebcce8df6146c0c3af1ff31b3eab34e99022fe9288cce14f96b0219d3df08f4199c5e1afba25e391f66ba75de337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
