# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b147deea35987b5f67edda731e895336e7840ae7d515e7e3baed7252e2eedf977c79a4a4bb9652b8a91f48e26e35a7a03d9b490bb3aeb9b41aa621fd680a44

test:
  secret_key_base: d75ca6dd47de79f64ec24aba9fa9cfb7aac7967dfe992106532e0a2aa25d0441b534947e74797ce30b7336614ee5c640f168c4f2ed183fd5f492bac3e2816111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
